import React, { useState, useEffect } from "react";
import { Link, useParams, useNavigate } from "react-router-dom";
import { supabase } from "../../../supabaseClient";
import { toast, Toaster } from "react-hot-toast";
import { FaArrowLeft, FaDownload, FaEdit, FaHistory, FaTimes, FaList } from "react-icons/fa";
import jsPDF from "jspdf";
import "jspdf-autotable";

const PurchaseDetails = ({ user }) => {
  const { id } = useParams();
  const navigate = useNavigate();

  const [purchase, setPurchase] = useState(null);
  const [items, setItems] = useState([]);
  const [loading, setLoading] = useState(true);
  const [downloading, setDownloading] = useState(false);
  const [error, setError] = useState(null);

  const totalAmount = items.reduce(
    (sum, item) => sum + item.quantity * item.unit_price,
    0
  );

  // -------------------------------------------
  // Fetch details
  // -------------------------------------------
  const fetchPurchaseDetails = async () => {
    setLoading(true);
    try {
      const { data: purchaseData, error: purchaseError } = await supabase
  .from("purchases")
  .select(`
    *,
    suppliers!inner(name, contact_person, phone, email)
  `)
  .eq("id", id)
  .single();


      if (purchaseError) throw purchaseError;
      setPurchase(purchaseData);

      const { data: itemsData, error: itemsError } = await supabase
        .from("purchase_items")
        .select(`
          *,
          products(name)
        `)
        .eq("purchase_id", id);

      if (itemsError) throw itemsError;

      setItems(itemsData);
    } catch (err) {
      console.error(err);
      setError("Failed to fetch purchase details: " + err.message);
      toast.error("Failed to fetch details");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (id) fetchPurchaseDetails();
  }, [id]);

  // -------------------------------------------
  // DOWNLOAD PDF FUNCTION
  const handleDownloadPDF = () => {
  if (!purchase || !items) return;

  setDownloading(true);

  try {
    const doc = new jsPDF("p", "pt");

    // ---------------------------
    // HEADER with Dark Blue
    // ---------------------------
    const pageWidth = doc.internal.pageSize.getWidth();
    doc.setFillColor(10, 35, 80); // dark blue
    doc.rect(0, 0, pageWidth, 60, "F"); // header bg

    doc.setFontSize(24);
    doc.setTextColor(255, 255, 255);
    doc.setFont(undefined, "bold");
    doc.text("Purchase Invoice", 40, 40);

    // ---------------------------
    // Footer note
    // ---------------------------
    const pageHeight = doc.internal.pageSize.getHeight();
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(
      "Generated by Pharmacy System | Thank you for your business",
      40,
      pageHeight - 20
    );

    // ---------------------------
    // PURCHASE INFO BOX
    // ---------------------------
    const startY = 80;
    doc.setFillColor(230, 230, 250); // light lavender background
    doc.roundedRect(35, startY, pageWidth - 70, 70, 6, 6, "F");

    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.setFont(undefined, "normal");
    doc.text(`Invoice Number: ${purchase.invoice_number}`, 45, startY + 20);
    doc.text(
      `Purchase Date: ${new Date(purchase.created_at).toLocaleString()}`,
      45,
      startY + 35
    );
    doc.text(`Supplier: ${purchase.suppliers?.name || "-"}`, 45, startY + 50);

    if (purchase.suppliers) {
      doc.setFontSize(10);
      doc.text(
        `Contact: ${purchase.suppliers.contact_person || "-"} | Phone: ${
          purchase.suppliers.phone || "-"
        } | Email: ${purchase.suppliers.email || "-"}`,
        45,
        startY + 65
      );
    }

    // ---------------------------
    // ITEMS TABLE
    // ---------------------------
    const tableData = items.map((item) => [
      item.products?.name || "-",
      item.quantity,
      item.unit_price.toLocaleString(),
      (item.quantity * item.unit_price).toLocaleString(),
    ]);

    doc.autoTable({
      startY: startY + 90,
      head: [["Product", "Qty", "Unit Price", "Total"]],
      body: tableData,
      theme: "striped",
      headStyles: {
        fillColor: [10, 35, 80], // dark blue
        textColor: 255,
        fontStyle: "bold",
      },
      alternateRowStyles: { fillColor: [240, 248, 255] }, // light row bg
      styles: {
        fontSize: 11,
        cellPadding: 6,
      },
    });

    // ---------------------------
    // TOTAL HIGHLIGHT
    // ---------------------------
    const finalY = doc.lastAutoTable.finalY || startY + 90;
    doc.setFontSize(14);
    doc.setFont(undefined, "bold");
    doc.setTextColor(10, 35, 80);
    doc.text(`TOTAL: ${totalAmount.toLocaleString()}`, pageWidth - 150, finalY + 25);

    // ---------------------------
    // Download PDF
    // ---------------------------
    doc.save(`purchase_${purchase.id}.pdf`);
    toast.success("PDF generated successfully!");
  } catch (err) {
    console.error("PDF generation error:", err);
    toast.error("Failed to generate PDF");
  } finally {
    setDownloading(false);
  }
};

const SummaryCard = ({ title, value, valueColor }) => (
  <div
    className={`
      bg-white border border-[#e5e7eb] rounded-[4px] px-5 py-4
      flex flex-col items-center justify-center
      transition-all duration-200
      hover:bg-[#fdfdfd]
      transform hover:-translate-y-[2px] active:translate-y-[1px]
      shadow-[0_1px_0px_0_rgba(0,0,0,0.2)]
      font-sans
      w-full
    `}
    style={{ willChange: 'transform' }}
  >
    <p className="text-gray-500 text-[11px] md:text-sm tracking-wide">{title}</p>
    <p className={`text-xl font-semibold mt-1 ${valueColor || "text-[#2563EB]"}`}>{value}</p>
  </div>
);

const CustomCard = ({ title, children }) => (
  <div className={`
      bg-white border border-[#e5e7eb] rounded-[4px] px-5 py-4
      flex flex-col items-start justify-center
      transition-all duration-200
      hover:bg-[#fdfdfd]
      transform hover:-translate-y-[2px] active:translate-y-[1px]
      shadow-[0_1px_0px_0_rgba(0,0,0,0.2)]
      font-sans
      w-full
  `}>
    {title && <p className="text-gray-500 text-[11px] md:text-sm tracking-wide mb-2">{title}</p>}
    {children}
  </div>
);


  // -------------------------------------------
  // UI STARTS
  // -------------------------------------------

  if (loading)
    return (
      <p className="p-6 text-gray-600 animate-pulse text-center text-lg">
        Loading purchase details...
      </p>
    );

  if (error)
    return (
      <p className="p-6 text-red-600 font-semibold text-center text-lg">
        {error}
      </p>
    );

  if (!purchase)
    return (
      <p className="p-6 text-gray-600 text-center text-lg">
        No purchase details found.
      </p>
    );

  return (
  <div className="min-h-screen p-4 sm:p-6 bg-gray-50 font-sans">
    <Toaster position="top-right" />

    <div className="max-w-4xl mx-auto flex flex-col gap-4">

      {/* KADI YA KICHWA */}
      <CustomCard>
        <div className="flex items-center justify-between w-full">
          <h1 className="text-2xl sm:text-3xl font-bold text-[#2563EB] flex items-center gap-2">
            <FaList /> Maelezo ya Manunuzi
          </h1>

          <Link
            to="../purchases"
            className="text-[#2563EB] font-semibold hover:underline flex items-center gap-2"
          >
            <FaArrowLeft /> Rudi
          </Link>
        </div>
      </CustomCard>

      {/* KADIRI YA PDF */}
      <CustomCard>
        <div className="flex justify-end w-full">
          <button
            onClick={handleDownloadPDF}
            disabled={downloading}
            className="
              bg-[#2563EB] text-white px-5 py-2 rounded-[4px]
              shadow hover:bg-red-600 flex items-center gap-2
              transition-all hover:-translate-y-[2px]
            "
          >
            <FaDownload />
            {downloading ? "Inatengenezwa..." : "Pakua PDF"}
          </button>
        </div>
      </CustomCard>

      {/* INFO YA SUPPLIER */}
      <CustomCard title="Taarifa za Supplier">
        <p className="text-gray-700 text-sm">{purchase.suppliers?.name || "-"}</p>

        {purchase.suppliers && (
          <div className="text-sm text-gray-600 space-y-1 mt-2">
            <p>Mawasiliano: {purchase.suppliers.contact_person || "-"}</p>
            <p>Simu: {purchase.suppliers.phone || "-"}</p>
            <p>Email: {purchase.suppliers.email || "-"}</p>
          </div>
        )}
      </CustomCard>

      {/* INFO YA MANUNUZI */}
      <CustomCard title="Maelezo ya Manunuzi">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 w-full">
          <div>
            <h2 className="text-gray-600 text-sm font-medium">Namba ya Vocha</h2>
            <p>{purchase.invoice_number}</p>
          </div>

          <div>
            <h2 className="text-gray-600 text-sm font-medium">Tarehe ya Manunuzi</h2>
            <p>{new Date(purchase.created_at).toLocaleString()}</p>
          </div>
        </div>
      </CustomCard>

      {/* JEDWALI LA BIDHAA */}
      <CustomCard title="Bidhaa Zilizonunuliwa">
        <div className="overflow-x-auto w-full">
          <table className="min-w-full border border-gray-200 rounded-lg text-sm">
            <thead className="bg-[#2563EB] text-white">
              <tr>
                <th className="px-4 py-2 text-left">Bidhaa</th>
                <th className="px-4 py-2 text-left">Idadi</th>
                <th className="px-4 py-2 text-left">Bei ya Kila Moja</th>
                <th className="px-4 py-2 text-left">Jumla</th>
              </tr>
            </thead>

            <tbody>
              {items.map((item) => (
                <tr key={item.id} className="border-t hover:bg-gray-50">
                  <td className="px-4 py-2">{item.products?.name || "-"}</td>
                  <td className="px-4 py-2">{item.quantity}</td>
                  <td className="px-4 py-2">{item.unit_price.toLocaleString()}</td>
                  <td className="px-4 py-2">
                    {(item.quantity * item.unit_price).toLocaleString()}
                  </td>
                </tr>
              ))}
            </tbody>

            <tfoot>
              <tr className="bg-gray-100 font-bold text-[#2563EB]">
                <td className="px-4 py-2 text-right" colSpan={3}>JUMLA YA KIWANGO</td>
                <td className="px-4 py-2 text-lg">
                  {totalAmount.toLocaleString()}
                </td>
              </tr>
            </tfoot>
          </table>
        </div>
      </CustomCard>

      {/* VITENDO */}
      <CustomCard>
        <div className="flex flex-wrap gap-2">

          {/* Hariri */}
          <Link
            to={`../purchases/edit/${id}`}
            className="
              bg-[#2563EB] text-white px-6 py-2 rounded-[4px]
              flex items-center gap-2 shadow hover:bg-red-600
              transition-all hover:-translate-y-[2px]
            "
          >
            <FaEdit />
            Hariri Manunuzi
          </Link>

          {/* Historia */}
          <Link
            to={`../purchases/history/${id}`}
            className="
              bg-white border border-[[#2563EB] text-[#2563EB]
              px-6 py-2 rounded-[4px] flex items-center gap-2
              hover:bg-red-50
              transition-all hover:-translate-y-[2px]
            "
          >
            <FaHistory />
            Angalia Historia
          </Link>

          {/* Funga */}
          <Link
            to="../purchases"
            className="
              bg-gray-200 px-6 py-2 rounded-[4px] text-gray-700
              flex items-center gap-2 hover:bg-gray-300
              transition-all hover:-translate-y-[2px]
            "
          >
            <FaTimes />
            Funga
          </Link>

        </div>
      </CustomCard>

    </div>
  </div>
);


};

export default PurchaseDetails;
